---
user: "vagrant"

vm:
  hostname: "pizaid-server"
  private_ip: "192.168.33.20"
  home: "/home/{{ user }}"

rbenv:
  repo: "git@github.com:sstephenson"
  ruby_version: 2.1.2

pizaid:
  interface_repo:  "git@github.com:Pizaid/pizaid-interface.git"
  controller_repo: "git@github.com:Pizaid/pizaid-controller.git"
  interface_path:  "{{ vm.home }}/pizaid/interface"
  controller_path: "{{ vm.home }}/pizaid/controller"
  interface_root:  "{{ vm.home }}/pizaid/interface/pizaid"
