- name: Install bundler via rbenv
  command: rbenv exec gem install bundler

- name: Install gems by bundle install
  command: bundle install --path vendor/bundler
  args:
    chdir: "{{ pizaid.controller_path }}"

- name: Install controller by rake install
  command: bundle exec rake install
  args:
    chdir: "{{ pizaid.controller_path }}"

- name: Install thrift
  sudo: yes
  pip: name=thrift
  notify: Start controller server
